package com.rafael.inclusimap.feature.auth.domain.model

import androidx.compose.ui.graphics.ImageBitmap
import com.rafael.inclusimap.core.domain.model.DeleteProcess

data class LoginState(
    val user: User? = null,
    val isNewUser: Boolean = false,
    val userPathID: String? = null,
    val isLoggedIn: Boolean = true,
    val isRegistering: Boolean = false,
    val isUpdatingPassword: Boolean = false,
    val isSamePassword: Boolean = false,
    val isPasswordChanged: Boolean = false,
    val isLoginOut: Boolean = false,
    val isDeletingAccount: Boolean = false,
    val deleteStep: DeleteProcess = DeleteProcess.NO_OP,
    val isAccountDeleted: Boolean = false,
    val userAlreadyRegistered: Boolean = true,
    val isPasswordCorrect: Boolean = true,
    var networkError: Boolean = false,
    val isUpdatingProfilePicture: Boolean = false,
    val isErrorUpdatingProfilePicture: Boolean = false,
    val isProfilePictureUpdated: Boolean = true,
    val isUpdatingUserName: Boolean = false,
    val isErrorUpdatingUserName: Boolean = false,
    val isUserNameUpdated: Boolean = true,
    val isAllowingPictureOptedIn: Boolean = false,
    val isErrorAllowingPictureOptedIn: Boolean = false,
    val isPictureOptedInSuccessfullyChanged: Boolean = true,
    val isRemovingProfilePicture: Boolean = false,
    val isErrorRemovingProfilePicture: Boolean = false,
    val isProfilePictureRemoved: Boolean = true,
    val userProfilePicture: ImageBitmap? = null,
    val recoveryToken: String? = null,
    val tokenHash: String? = null,
    val isTokenValid: Boolean = false,
    val tokenExpirationTime: Long? = null,
    val isSendingEmail: Boolean = false,
    val isEmailSent: Boolean = false,
    val isValidatingToken: Boolean = false,
    val isTokenValidated: Boolean = false,
    val tokenExpirationTimer: Long? = null,
)
